build:
  environment:
    php: 7.4.14

  dependencies:
    override:
      - composer install --no-progress --no-suggest --no-interaction --ignore-platform-reqs

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

tools:
  external_code_coverage: true

checks:
  php: true
